import { Barlow } from "next/font/google";
import "./globals.css";
import { Layouts } from "@/components/common/Layouts";

const inter = Barlow({ 
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
   });

export const metadata = {
  title: "House Journey Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, shrink-to-fit=no"/>
        <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon"/>  
      </head>
      <body className={inter.className}>
        {/* {children} */}
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
